In [ ]:
"""
array-> array()-->
numpy->install
An Array represents a group of elements of same data type.
Single Dimensional Array(1D Array):
a single row or single Col of elements.

Ex.marks obtained by student in 5 subjects.
50,51,53,55
or 50,
51,
52,
53,
54,

"""

In [ ]:
#Using Arrray function
lst=[10,20,30,48,58,65]
type(lst)
import numpy as np
a=np.array(lst)
print(type(a))
print(a)
for i in a:print(i)


In [ ]:
#Array example Using String
import numpy 
b =numpy.array([2.3,4.3,5.4,6.4,7.8,9.8])
print(b)

myarray=numpy.array(['firoz','python','heloo'])
myarray
for i in myarray:
    print(i)

In [ ]:
#passing the direct string to array


In [ ]:
#2)using linspace() function to create array
""" 
To divide a range between some points.
linspace(s,e,nos of division i.e 5 parts)
#both the extreme ands are included
"""
from numpy import *
arr =linspace(0,100,100)
print(arr)
for i in arr:print(i)

In [71]:
#3) array by using logspace function 
arr1=logspace(1,100,5)
print(arr1)

[  1.00000000e+001   5.62341325e+025   3.16227766e+050   1.77827941e+075
   1.00000000e+100]


In [72]:
#3) Array range function i.e arange
"""
arange(5,10,2)# 2 is step size it can be positive or negative

"""
arr2=arange(10,20,3)
print(arr2)
for i in arr2:
    print(i)

[10 13 16 19]
10
13
16
19


In [ ]:
arr=zeros(6,int)
arr1=zeros(6)
print(arr)
print(arr1)#default data type is float

In [ ]:
#operation on array
from numpy import *
arr=array([10,40,15,25,20])
arr_result=arr*5
print(arr_result)
substr=arr_result-10
print(substr)


#concatination in array
arr1=array([100,89,78])
x=concatenate([arr,arr1]) 
print(x)

In [ ]:
#square of the number
array_num=array([10,20,45,6,78,90])
array_num
sort(array_num)

#x=sum(array_num)
#sqrt(x)
n=argmin(array_num)
n
#argmin()


In [ ]:
#Alias in the array
from numpy import *
a=array([10,20,30,60])
b=a
print(a)
print(b)
a[3]
a[0]=88# change the array element


In [153]:
"""
Hw to create the view of an array will be usefull in creating mirror servers ex flipkar or any big website
it can be done by view() it is also called  shallow copy
deep copy:change in one array will not effect in  other array
"""
from numpy import *
a=[10,23,4,5,7]
c=a.view # shallow copying
print(c)
# b=a.copy() #deep copying
# print(b)
# a[0]=1000
# print(a)


AttributeError: 'list' object has no attribute 'view'

In [86]:
from numpy import *
arr=array([3,4,5,6,7,8,2,])
print(arr)
print(arr.ndim)
arr.shape

[3 4 5 6 7 8 2]
1


(7,)

In [93]:
#2 d array 

arr1=array([[1,2,3,4,5],[4,5,6,73,4]])
print(arr1)
print(arr1.ndim)
arr1.shape #shape will give number of rows and columns
arr1.shape=(2,2)

[[ 1  2  3  4  5]
 [ 4  5  6 73  4]]
2


ValueError: cannot reshape array of size 10 into shape (2,2)

In [96]:
x=array([1,2,3,4,5,6])
x.itemsize

arr.nbytes#
arr.dtype#

dtype('int64')

In [102]:
#reshape() method
from numpy import *
arr =arange(10)
print(arr)
arr=arange(9)
arr
arr.reshape(3,3)#use to create 1d array to 2 dimensional


[0 1 2 3 4 5 6 7 8 9]


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [109]:
print(arr)
arr2=arr.reshape(3,3)
print(arr2)

x=arr2.flatten() #flatten() will convert 2 d array to 1 d array
print(x)


[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 3 4 5 6 7 8]


In [ ]:
"""
A 2D array represents more than 1 row and more than 1 col
ex:marks obtained by group of students in 5 subjects.
40,42,43,44,45,46
54,55,56,76,45,47
72,75,78,90,65,45
A 2 Dimensional is combination of several 1 Dimensional array
"""

In [110]:
"""
How to crate 2D array in python


"""
from numpy import *
arr=array([[1,2,3,4],[5,6,7],[7,8,9,0]])
print(arr)

[list([1, 2, 3, 4]) list([5, 6, 7]) list([7, 8, 9, 0])]


In [117]:
"""Write a python programme to display to display 2 D array in the form of the matrix"""

from numpy import *
arr=array([[1,2,3,4],[5,6,7],[7,8,9,0]])
#display row-wise
for i in range(len(arr)):
    print(arr[i])
##display element-wise and in matrix form using for loop
for i in range(len(arr)):
    for j in range(len(arr[i])):
        print(arr[i][j], end=' ')
    print()

[1, 2, 3, 4]
[5, 6, 7]
[7, 8, 9, 0]
1 2 3 4 
5 6 7 
7 8 9 0 


In [121]:
##
arr = ones((2,3))
print(arr)

arr1=zeros((2,3),dtype=int)
print(arr1)

[[ 1.  1.  1.]
 [ 1.  1.  1.]]
[[0 0 0]
 [0 0 0]]


In [122]:
#eye() willl create a 2 d function 
arr =eye(4,dtype=int)
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [131]:
#Indexing and slicing is possible in 2D arrays

from numpy import *
arr =array([[1,2,3,4],[5,6,7,1],[4,5,6,7]])
print(arr)
print(arr[0]) #retervice o row
print(arr[2])
print(arr[0,0])
print(arr[0,1])
print(arr[0,3])

[[1 2 3 4]
 [5 6 7 1]
 [4 5 6 7]]
[1 2 3 4]
[4 5 6 7]
1
2
4


In [ ]:
#Slicing example in array
"""
    1 2 3 4
    5 6 1 2 
    1 0 3 2
    
arr[0:2,2:4]
o/p: 
arr[1:3,0:3]

o/p  5 6 1 
     1 0 3 
"""

In [133]:
#How to convert 2D array to matrix
m=matrix(arr)
print(m)

[[1 2 3 4]
 [5 6 7 1]
 [4 5 6 7]]


In [134]:
# 2 Matix Multiplication programe
from numpy import *
a= array([[1,2,3,4,5],[6,7,8,9,0]])
b=array([[1,0],[2,2],[3-1]])
m1=matrix(a)
m1=m1+10
m2=matrix(b)
print(m_out=m1*m2)

ValueError: shapes (2,5) and (1,3) not aligned: 5 (dim 1) != 1 (dim 0)

In [136]:
#Accept matrix elements form keyboard and display its Transpose

from numpy import *
r,c=[int(x) for x in input('Enter rows and cols:').split(',')]
arr=zeros((r,c))
for r in range(r):
    arr[i]=[flot(x) for x in input().split()]
    m=matrix(arr)
    print('Transpose=')
    print(m.transpose())

Enter rows and cols:2,3
1 2 3 


NameError: name 'flot' is not defined