In [1]:
import numpy as np
import pandas as pd
Seasons = ["2005","2006","2007","2008","2009","2010","2011","2012","2013","2014"]
Sdict ={"2005":0,"2006":1,"2007":2,"2008":3,"2009":4,"2010":5,"2011":6,"2012":7,"2013":8,"2014":9}
#Players list
Players =["KobeBryant","JoeJohnson","LeBronJames","CarmeloAnthony","DwightHoward","ChrisBosh",
          "ChrisPaul","KevinDurant","DerrickRose","DwayneWade"]

Pdict ={"KobeBryant":0,"JoeJohnson":1,"LeBronJames":2,"CarmeloAnthony":3,"DwightHoward":4,"ChrisBosh":5,
        "ChrisPaul":6,"KevinDurant":7,"DerrickRose":8,"DwayneWade":9}

In [2]:
#Salaies till 12 months
KobeBryant_Salary =[15946875,17718750,19490625,21262500,23034375,24806250,25244493,27849149,30453805,23500000]
JoeJohnson_Salary =[12000000,12744189,13488377,14232567,14976754,16324500,18038573,19752645,21466718,23180790]
LeBronJames_Salary =[4621800,5828090,13041250,14410581,15779912,14500000,16022500,17545000,19067500,20644400]
CarmeloAnthony_Salary=[3713640,4694041,13041250,14410581,15779912,17149243,18518574,19450000,22407474,22458000]
DwightHoward_Salary =[4493160,4806720,6061274,13758000,15202590,16647180,18091770,19536360,20513178,21436271]
ChrisBosh_Salary =[3348000,4235220,12455000,14410581,15779912,14500000,16022500,17545000,19067500,20644400]
ChrisPaul_Salary =[3144240,3380160,3615960,4574189,13520500,14940153,16359805,17779458,18668431,20068563]
KevinDurant_Salary =[0,0,4171200,4484040,4796880,6053663,15506632,16669630,17832627,18995624]
DerrickRose_Salary = [0,0,0,4822800,5184480,5546160,6993708,16402500,17632688,18862875]
DwayneWade_Salary =[3031920,3841443,13041250,14410581,15779912,14200000,15691000,17182000,18673000,15000000]


In [3]:
import numpy as np
#Matrix
Salary = np.array([KobeBryant_Salary, JoeJohnson_Salary, LeBronJames_Salary,
CarmeloAnthony_Salary, DwightHoward_Salary, ChrisBosh_Salary, ChrisPaul_Salary,
KevinDurant_Salary, DerrickRose_Salary, DwayneWade_Salary])
Salary


array([[15946875, 17718750, 19490625, 21262500, 23034375, 24806250,
        25244493, 27849149, 30453805, 23500000],
       [12000000, 12744189, 13488377, 14232567, 14976754, 16324500,
        18038573, 19752645, 21466718, 23180790],
       [ 4621800,  5828090, 13041250, 14410581, 15779912, 14500000,
        16022500, 17545000, 19067500, 20644400],
       [ 3713640,  4694041, 13041250, 14410581, 15779912, 17149243,
        18518574, 19450000, 22407474, 22458000],
       [ 4493160,  4806720,  6061274, 13758000, 15202590, 16647180,
        18091770, 19536360, 20513178, 21436271],
       [ 3348000,  4235220, 12455000, 14410581, 15779912, 14500000,
        16022500, 17545000, 19067500, 20644400],
       [ 3144240,  3380160,  3615960,  4574189, 13520500, 14940153,
        16359805, 17779458, 18668431, 20068563],
       [       0,        0,  4171200,  4484040,  4796880,  6053663,
        15506632, 16669630, 17832627, 18995624],
       [       0,        0,        0,  4822800,  5184480,  55461

In [4]:
#Number of Games played by player

KobeBryant_G = [80,77,82,82,73,82,58,78,6,35]
JoeJohnson_G = [82,57,82,79,76,72,60,72,79,80]
LeBronJames_G = [79,78,75,81,76,79,62,76,77,69]
CarmeloAnthony_G = [80,65,77,66,69,77,55,67,77,40]
DwightHoward_G = [82,82,82,79,82,78,54,76,71,41]
ChrisBosh_G = [70,69,67,77,70,77,57,74,79,44]
ChrisPaul_G = [78,64,80,78,45,80,60,70,62,82]
KevinDurant_G = [35,35,80,74,82,78,66,81,81,27]
DerrickRose_G = [40,40,40,81,78,81,39,0,10,51]
DwayneWade_G = [75,51,51,79,77,76,49,69,54,62]

In [5]:
#Array of games played

Games = np.array([KobeBryant_G, JoeJohnson_G, LeBronJames_G, CarmeloAnthony_G,
                  DwightHoward_G, ChrisBosh_G, ChrisPaul_G, KevinDurant_G, DerrickRose_G, DwayneWade_G])
print(Games)

[[80 77 82 82 73 82 58 78  6 35]
 [82 57 82 79 76 72 60 72 79 80]
 [79 78 75 81 76 79 62 76 77 69]
 [80 65 77 66 69 77 55 67 77 40]
 [82 82 82 79 82 78 54 76 71 41]
 [70 69 67 77 70 77 57 74 79 44]
 [78 64 80 78 45 80 60 70 62 82]
 [35 35 80 74 82 78 66 81 81 27]
 [40 40 40 81 78 81 39  0 10 51]
 [75 51 51 79 77 76 49 69 54 62]]


In [6]:
#Minutes Played by players
KobeBryant_MP = [3277,3140,3192,2960,2835,2779,2232,3013,177,1207]
JoeJohnson_MP = [3340,2359,3343,3124,2886,2554,2127,2642,2575,2791]
LeBronJames_MP = [3361,3190,3027,3054,2966,3063,2326,2877,2902,2493]
CarmeloAnthony_MP = [2941,2486,2806,2277,2634,2751,1876,2482,2982,1428]
DwightHoward_MP = [3021,3023,3088,2821,2843,2935,2070,2722,2396,1223]
ChrisBosh_MP = [2751,2658,2425,2928,2526,2795,2007,2454,2531,1556]
ChrisPaul_MP = [2808,2353,3006,3002,1712,2880,2181,2335,2171,2857]
KevinDurant_MP = [1255,1255,2768,2885,3239,3038,2546,3119,3122,913]
DerrickRose_MP = [1168,1168,1168,3000,2871,3026,1375,0,311,1530]
DwayneWade_MP = [2892,1931,1954,3048,2792,2823,1625,2391,1775,1971]

In [7]:
#Matrix
MinutesPlayed = np.array([KobeBryant_MP, JoeJohnson_MP, LeBronJames_MP,
CarmeloAnthony_MP, DwightHoward_MP, ChrisBosh_MP, ChrisPaul_MP, KevinDurant_MP,
DerrickRose_MP, DwayneWade_MP])
MinutesPlayed

array([[3277, 3140, 3192, 2960, 2835, 2779, 2232, 3013,  177, 1207],
       [3340, 2359, 3343, 3124, 2886, 2554, 2127, 2642, 2575, 2791],
       [3361, 3190, 3027, 3054, 2966, 3063, 2326, 2877, 2902, 2493],
       [2941, 2486, 2806, 2277, 2634, 2751, 1876, 2482, 2982, 1428],
       [3021, 3023, 3088, 2821, 2843, 2935, 2070, 2722, 2396, 1223],
       [2751, 2658, 2425, 2928, 2526, 2795, 2007, 2454, 2531, 1556],
       [2808, 2353, 3006, 3002, 1712, 2880, 2181, 2335, 2171, 2857],
       [1255, 1255, 2768, 2885, 3239, 3038, 2546, 3119, 3122,  913],
       [1168, 1168, 1168, 3000, 2871, 3026, 1375,    0,  311, 1530],
       [2892, 1931, 1954, 3048, 2792, 2823, 1625, 2391, 1775, 1971]])

In [8]:
#Field Goals
KobeBryant_FG = [978,813,775,800,716,740,574,738,31,266]
JoeJohnson_FG = [632,536,647,620,635,514,423,445,462,446]
LeBronJames_FG = [875,772,794,789,768,758,621,765,767,624]
CarmeloAnthony_FG = [756,691,728,535,688,684,441,669,743,358]
DwightHoward_FG = [468,526,583,560,510,619,416,470,473,251]
ChrisBosh_FG = [549,543,507,615,600,524,393,485,492,343]
ChrisPaul_FG = [407,381,630,631,314,430,425,412,406,568]
KevinDurant_FG = [306,306,587,661,794,711,643,731,849,238]
DerrickRose_FG = [208,208,208,574,672,711,302,0,58,338]
DwayneWade_FG = [699,472,439,854,719,692,416,569,415,509]

In [9]:
#Matrix
FieldGoals = np.array([KobeBryant_FG, JoeJohnson_FG, LeBronJames_FG, CarmeloAnthony_FG,
DwightHoward_FG, ChrisBosh_FG, ChrisPaul_FG, KevinDurant_FG, DerrickRose_FG,
DwayneWade_FG])

FieldGoals

array([[978, 813, 775, 800, 716, 740, 574, 738,  31, 266],
       [632, 536, 647, 620, 635, 514, 423, 445, 462, 446],
       [875, 772, 794, 789, 768, 758, 621, 765, 767, 624],
       [756, 691, 728, 535, 688, 684, 441, 669, 743, 358],
       [468, 526, 583, 560, 510, 619, 416, 470, 473, 251],
       [549, 543, 507, 615, 600, 524, 393, 485, 492, 343],
       [407, 381, 630, 631, 314, 430, 425, 412, 406, 568],
       [306, 306, 587, 661, 794, 711, 643, 731, 849, 238],
       [208, 208, 208, 574, 672, 711, 302,   0,  58, 338],
       [699, 472, 439, 854, 719, 692, 416, 569, 415, 509]])

In [10]:
#Field Goal Attempts
KobeBryant_FGA = [2173,1757,1690,1712,1569,1639,1336,1595,73,713]
JoeJohnson_FGA = [1395,1139,1497,1420,1386,1161,931,1052,1018,1025]
LeBronJames_FGA = [1823,1621,1642,1613,1528,1485,1169,1354,1353,1279]
CarmeloAnthony_FGA = [1572,1453,1481,1207,1502,1503,1025,1489,1643,806]
DwightHoward_FGA = [881,873,974,979,834,1044,726,813,800,423]
ChrisBosh_FGA = [1087,1094,1027,1263,1158,1056,807,907,953,745]
ChrisPaul_FGA = [947,871,1291,1255,637,928,890,856,870,1170]
KevinDurant_FGA = [647,647,1366,1390,1668,1538,1297,1433,1688,467]
DerrickRose_FGA = [436,436,436,1208,1373,1597,695,0,164,835]
DwayneWade_FGA = [1413,962,937,1739,1511,1384,837,1093,761,1084]

In [11]:
#Matrix
import numpy as np
FieldGoalAttempts = np.array([KobeBryant_FGA, JoeJohnson_FGA, LeBronJames_FGA,
CarmeloAnthony_FGA, DwightHoward_FGA, ChrisBosh_FGA, ChrisPaul_FGA, KevinDurant_FGA,
DerrickRose_FGA, DwayneWade_FGA])
FieldGoalAttempts

array([[2173, 1757, 1690, 1712, 1569, 1639, 1336, 1595,   73,  713],
       [1395, 1139, 1497, 1420, 1386, 1161,  931, 1052, 1018, 1025],
       [1823, 1621, 1642, 1613, 1528, 1485, 1169, 1354, 1353, 1279],
       [1572, 1453, 1481, 1207, 1502, 1503, 1025, 1489, 1643,  806],
       [ 881,  873,  974,  979,  834, 1044,  726,  813,  800,  423],
       [1087, 1094, 1027, 1263, 1158, 1056,  807,  907,  953,  745],
       [ 947,  871, 1291, 1255,  637,  928,  890,  856,  870, 1170],
       [ 647,  647, 1366, 1390, 1668, 1538, 1297, 1433, 1688,  467],
       [ 436,  436,  436, 1208, 1373, 1597,  695,    0,  164,  835],
       [1413,  962,  937, 1739, 1511, 1384,  837, 1093,  761, 1084]])

In [12]:
#Score Points by player

KobeBryant_PTS = [2832,2430,2323,2201,1970,2078,1616,2133,83,782]
JoeJohnson_PTS = [1653,1426,1779,1688,1619,1312,1129,1170,1245,1154]
LeBronJames_PTS = [2478,2132,2250,2304,2258,2111,1683,2036,2089,1743]
CarmeloAnthony_PTS = [2122,1881,1978,1504,1943,1970,1245,1920,2112,966]
DwightHoward_PTS = [1292,1443,1695,1624,1503,1784,1113,1296,1297,646]
ChrisBosh_PTS = [1572,1561,1496,1746,1678,1438,1025,1232,1281,928]
ChrisPaul_PTS = [1258,1104,1684,1781,841,1268,1189,1186,1185,1564]
KevinDurant_PTS = [903,903,1624,1871,2472,2161,1850,2280,2593,686]
DerrickRose_PTS = [597,597,597,1361,1619,2026,852,0,159,904]
DwayneWade_PTS = [2040,1397,1254,2386,2045,1941,1082,1463,1028,1331]

In [13]:
#Matrix of points scored by players
Points = np.array([KobeBryant_PTS, JoeJohnson_PTS, LeBronJames_PTS, CarmeloAnthony_PTS,
DwightHoward_PTS, ChrisBosh_PTS, ChrisPaul_PTS, KevinDurant_PTS, DerrickRose_PTS,DwayneWade_PTS])
Points

array([[2832, 2430, 2323, 2201, 1970, 2078, 1616, 2133,   83,  782],
       [1653, 1426, 1779, 1688, 1619, 1312, 1129, 1170, 1245, 1154],
       [2478, 2132, 2250, 2304, 2258, 2111, 1683, 2036, 2089, 1743],
       [2122, 1881, 1978, 1504, 1943, 1970, 1245, 1920, 2112,  966],
       [1292, 1443, 1695, 1624, 1503, 1784, 1113, 1296, 1297,  646],
       [1572, 1561, 1496, 1746, 1678, 1438, 1025, 1232, 1281,  928],
       [1258, 1104, 1684, 1781,  841, 1268, 1189, 1186, 1185, 1564],
       [ 903,  903, 1624, 1871, 2472, 2161, 1850, 2280, 2593,  686],
       [ 597,  597,  597, 1361, 1619, 2026,  852,    0,  159,  904],
       [2040, 1397, 1254, 2386, 2045, 1941, 1082, 1463, 1028, 1331]])

In [14]:
import numpy as np
mydata = np.arange(0,20)
print(mydata)

reshape_data=np.reshape(mydata,(5,4))
print(reshape_data)
np.reshape(mydata,(5,4),order='C')
MATR1 = np.reshape(mydata,(5,4),order='C') #C represtent programming of c index number
MATR2 = np.reshape(mydata,(5,4),order='F') #Fortran  like index ordering
print(MATR2)

# In[24]:
# get 10 again
MATR2[0,2]
r1 = ['I','am','happy']
r2 = ['What','a','day']
r3 = [1,2,3]
[r1,r2,r3]
#import numpy as np
np.array([r1,r2,r3]) 
# #gives
print(np.array([r1,r2,r3]))


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]
[['I' 'am' 'happy']
 ['What' 'a' 'day']
 ['1' '2' '3']]


In [15]:
#Games ofGames[0] index vector
Games

array([[80, 77, 82, 82, 73, 82, 58, 78,  6, 35],
       [82, 57, 82, 79, 76, 72, 60, 72, 79, 80],
       [79, 78, 75, 81, 76, 79, 62, 76, 77, 69],
       [80, 65, 77, 66, 69, 77, 55, 67, 77, 40],
       [82, 82, 82, 79, 82, 78, 54, 76, 71, 41],
       [70, 69, 67, 77, 70, 77, 57, 74, 79, 44],
       [78, 64, 80, 78, 45, 80, 60, 70, 62, 82],
       [35, 35, 80, 74, 82, 78, 66, 81, 81, 27],
       [40, 40, 40, 81, 78, 81, 39,  0, 10, 51],
       [75, 51, 51, 79, 77, 76, 49, 69, 54, 62]])

In [16]:
Games[1,]

array([82, 57, 82, 79, 76, 72, 60, 72, 79, 80])

In [17]:
import numpy as np
np.array([])
re_arrange=np.reshape(mydata,(5,4))
print(re_arrange)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [18]:
#swapaxes(0,2) have to see swap axis
a = np.arange(18)
p=a.reshape(3,2,3)#.swapaxes(0,2)
#p=a.reshape(6,1,3).swapaxes(0,2)
#6 is a number of matrix to be formed rest is row and colomn respectively
print(p)
#print("hey wass up+",p)
#b = a.reshape(3,3,2).swapaxes(0,2)
print(a)
#print(b)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


In [19]:
# get 10 again
print(MATR2[0,2])
r1 = ['I','am','happy']
r2 = ['What','a','day']
r3 = [1,2,3]
[r1,r2,r3]

10


[['I', 'am', 'happy'], ['What', 'a', 'day'], [1, 2, 3]]

In [20]:
import numpy as np
np.array([r1,r2,r3]) #gives
print(np.array([r1,r2,r3]))
Games[0]
# Games[0] #Games ofGames[1] #Games of
# Games[2][9]
print(Games[2][-1])
# Games[2,-1]
print(Games[2,9])
# #here v have to know the position/index of the elements
# print(Games[2][9])

[['I' 'am' 'happy']
 ['What' 'a' 'day']
 ['1' '2' '3']]
69
69


In [21]:
# of respective matrix and this is tedious
Points
print(Points[6])
print(Pdict['KobeBryant'])
print(Games[0])
Pdict['DerrickRose']
Games[8]
Games[Pdict['DerrickRose']] 
# This is the row numberGames[Pdict['DerrickRose']] [7] 
# Here v r specifying the row and the col nums


[1258 1104 1684 1781  841 1268 1189 1186 1185 1564]
0
[80 77 82 82 73 82 58 78  6 35]


array([40, 40, 40, 81, 78, 81, 39,  0, 10, 51])

In [22]:
# Why do we get this here, is there a problem
# Games[Pdict['DerrickRose']] [Sdict['2012']]
# Games[Pdict['KobeBryant']] [Sdict['2012']]
# Points[Pdict['DerrickRose']] [Sdict['2012']]
# Points[Pdict['KobeBryant']] [Sdict['2012']]
# Points[Pdict['JoeJohnson']] [Sdict['2012']]
Points[Pdict['JoeJohnson']]

array([1653, 1426, 1779, 1688, 1619, 1312, 1129, 1170, 1245, 1154])

In [23]:
# Why do v get this here, is there a problem
#print(Games[Pdict['DerrickRose']] [Sdict['2012']])
#print(g)
#Games[ Pdict['KobeBryant'],Sdict['2012'] ]
#Points[Pdict['DerrickRose']] [Sdict['2012']]
Points[Pdict['KobeBryant']] [Sdict['2012']]
# Points[Pdict['JoeJohnson']] [Sdict['2012']]
# Points[Pdict['JoeJohnson']]



2133

In [24]:
Salary
Salary[Pdict['JoeJohnson']] [Sdict['2012']]
Salary[Pdict['LeBronJames']] [Sdict['2012']]
print(Pdict['LeBronJames'])
print(Sdict['2009'])
Salary[2][4]
Salary[Pdict['LeBronJames']] [Sdict['2009']]
print(FieldGoals)
print(Games)

2
4
[[978 813 775 800 716 740 574 738  31 266]
 [632 536 647 620 635 514 423 445 462 446]
 [875 772 794 789 768 758 621 765 767 624]
 [756 691 728 535 688 684 441 669 743 358]
 [468 526 583 560 510 619 416 470 473 251]
 [549 543 507 615 600 524 393 485 492 343]
 [407 381 630 631 314 430 425 412 406 568]
 [306 306 587 661 794 711 643 731 849 238]
 [208 208 208 574 672 711 302   0  58 338]
 [699 472 439 854 719 692 416 569 415 509]]
[[80 77 82 82 73 82 58 78  6 35]
 [82 57 82 79 76 72 60 72 79 80]
 [79 78 75 81 76 79 62 76 77 69]
 [80 65 77 66 69 77 55 67 77 40]
 [82 82 82 79 82 78 54 76 71 41]
 [70 69 67 77 70 77 57 74 79 44]
 [78 64 80 78 45 80 60 70 62 82]
 [35 35 80 74 82 78 66 81 81 27]
 [40 40 40 81 78 81 39  0 10 51]
 [75 51 51 79 77 76 49 69 54 62]]


In [25]:
# How do we get FieldGoals per Games
FieldGoals / Games
# Performs elem by elem division
# similar to vec opers in R
# Why are v getting divide by 0
# Is this an error or warning

/home/firoz/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([[ 12.225     ,  10.55844156,   9.45121951,   9.75609756,
          9.80821918,   9.02439024,   9.89655172,   9.46153846,
          5.16666667,   7.6       ],
       [  7.70731707,   9.40350877,   7.8902439 ,   7.84810127,
          8.35526316,   7.13888889,   7.05      ,   6.18055556,
          5.84810127,   5.575     ],
       [ 11.07594937,   9.8974359 ,  10.58666667,   9.74074074,
         10.10526316,   9.59493671,  10.01612903,  10.06578947,
          9.96103896,   9.04347826],
       [  9.45      ,  10.63076923,   9.45454545,   8.10606061,
          9.97101449,   8.88311688,   8.01818182,   9.98507463,
          9.64935065,   8.95      ],
       [  5.70731707,   6.41463415,   7.1097561 ,   7.08860759,
          6.2195122 ,   7.93589744,   7.7037037 ,   6.18421053,
          6.66197183,   6.12195122],
       [  7.84285714,   7.86956522,   7.56716418,   7.98701299,
          8.57142857,   6.80519481,   6.89473684,   6.55405405,
          6.2278481 ,   7.79545455],
       [  

In [26]:
import warnings
warnings.filterwarnings('ignore') 
#ignoring the warning
print(FieldGoals/Games)
print(round(FieldGoals/Games,2))
#print(np.matrix.round(FieldGoals/Games))
#FieldGoalsPerGame = np.matrix.round(FieldGoals / Games)
# print(FieldGoalsPerGame)
# FieldGoalsPerGame[Pdict['LeBronJames']] [Sdict['2009']]
# FieldGoalsPerGame[Pdict['KobeBryant']] [Sdict['2009']]
# np.matrix.round(MinutesPlayed) #ntc KB has 177 mins & DR has 0,311
# print(np.matrix.round(Games))
# print(np.matrix.round(MinutesPlayed/Games))
# # What does 0 mean

[[ 12.225       10.55844156   9.45121951   9.75609756   9.80821918
    9.02439024   9.89655172   9.46153846   5.16666667   7.6       ]
 [  7.70731707   9.40350877   7.8902439    7.84810127   8.35526316
    7.13888889   7.05         6.18055556   5.84810127   5.575     ]
 [ 11.07594937   9.8974359   10.58666667   9.74074074  10.10526316
    9.59493671  10.01612903  10.06578947   9.96103896   9.04347826]
 [  9.45        10.63076923   9.45454545   8.10606061   9.97101449
    8.88311688   8.01818182   9.98507463   9.64935065   8.95      ]
 [  5.70731707   6.41463415   7.1097561    7.08860759   6.2195122
    7.93589744   7.7037037    6.18421053   6.66197183   6.12195122]
 [  7.84285714   7.86956522   7.56716418   7.98701299   8.57142857
    6.80519481   6.89473684   6.55405405   6.2278481    7.79545455]
 [  5.21794872   5.953125     7.875        8.08974359   6.97777778   5.375
    7.08333333   5.88571429   6.5483871    6.92682927]
 [  8.74285714   8.74285714   7.3375       8.93243243   9.682

TypeError: type numpy.ndarray doesn't define __round__ method

In [ ]:
# What does 0 mean
#FieldGoals
FieldGoalAttempts

In [ ]:
# What is FG / FGAs?
FieldGoals / FieldGoalAttempts
from __future__ import division
print(FieldGoals/FieldGoalAttempts)
# Visualizations
np.matrix.round(FieldGoals/FieldGoalAttempts,2)*100
# What are some of the problems from the above matrxi
# We cannot see the trends
# We do not know which players data we are looking at
# We do not know the patterns of the players
# How they are peforming etc

In [ ]:
# Visualizations
import matplotlib.pyplot as plt
#get_ipython().magic(u'matplotlib inline')
plt.plot(Salary[0])
Salary[0]
plt.plot(Salary[0],c='Green') # c is for color
plt.plot(Salary[0],c='Black', ls='--') # ls is for line style
plt.plot(Salary[0],c='Black', ls='--', marker='s') # s stands for square
plt.plot(Salary[0],c='Black', ls='--', marker='s', ms=2) # ms stands for marker size
plt.plot(Salary[0],c='Black', ls='--', marker='s', ms=7) # ms stands for marker size
plt.show()

In [ ]:
plt.rcParams['figure.figsize'] = 2,1
plt.plot(Salary[0],c='Black', ls='--', marker='s', ms=7) # ms stands for marker size
plt.show()

In [ ]:
# Advanced Visualizations
plt.rcParams['figure.figsize'] = 8,4
plt.plot(Salary[0],c='Black', ls='--', marker='s', ms=7) # ms stands for marker size
plt.show()

In [ ]:
plt.plot(Salary[0],c='Black', ls='--', marker='s', ms=7) # ms stands for marker size
plt.xticks(list(range(0,9)),Seasons)
plt.show()

In [ ]:
plt.plot(Salary[0],c='Black', ls='--', marker='s', ms=7) 
# ms stands for marker sizeplt.xticks(list(range(0,10)),Seasons,rotation='vertical')
plt.show()

In [ ]:
plt.plot(Salary[0],c='Black', ls='--', marker='s', ms=7, label=Players[0])
plt.xticks(list(range(0,9)),Seasons)
plt.show()

In [ ]:
plt.plot(Salary[0],c='Black', ls='--', marker='s', ms=7, label=Players[0])
plt.plot(Salary[1],c='Red', ls='--', marker='s', ms=10, label=Players[1])
plt.xticks(list(range(0,9)),Seasons)
#seasons is list object
plt.show()

In [ ]:
plt.

In [ ]:

plt.plot(Salary[0],c='Black', ls='--', marker='s', ms=7, label=Players[0])
plt.plot(Salary[1],c='Red', ls='--', marker='o', ms=7, label=Players[1])
plt.xticks(list(range(0,9)),Seasons)
plt.show()

In [ ]:
plt.plot(Salary[0],c='Black', ls='--', marker='s', ms=7, label=Players[0])
plt.plot(Salary[1],c='Red', ls='--', marker='o', ms=7, label=Players[1])
plt.plot(Salary[2],c='Green', ls='--', marker='^', ms=7, label=Players[2])
plt.plot(Salary[3],c='Blue', ls='--', marker='D', ms=7, label=Players[3])
plt.xticks(list(range(0,9)),Seasons)
plt.show()

In [ ]:
plt.plot(Salary[0],c='Black', ls='--', marker='s', ms=7, label=Players[0])
plt.plot(Salary[1],c='Red', ls='--', marker='o', ms=7, label=Players[1])
plt.plot(Salary[2],c='Green', ls='--', marker='^', ms=7, label=Players[2])
plt.plot(Salary[3],c='Blue', ls='--', marker='D', ms=7, label=Players[3])
plt.legend() # legend
plt.xticks(list(range(0,9)),Seasons)
plt.show()

In [ ]:
plt.plot(Salary[0],c='Black', ls='--', marker='s', ms=7, label=Players[0])
plt.plot(Salary[1],c='Red', ls='--', marker='o', ms=7, label=Players[1])
plt.plot(Salary[2],c='Green', ls='--', marker='^', ms=7, label=Players[2])
plt.plot(Salary[3],c='Blue', ls='--', marker='D', ms=7, label=Players[3])
plt.legend(loc='upper left') # legend
plt.xticks(list(range(0,9)),Seasons)
plt.show()

In [ ]:
plt.plot(Salary[0],c='Black', ls='--', marker='s', ms=7, label=Players[0])
plt.plot(Salary[1],c='Red', ls='--', marker='o', ms=7, label=Players[1])
plt.plot(Salary[2],c='Green', ls='--', marker='^', ms=7, label=Players[2])
plt.plot(Salary[3],c='Blue', ls='--', marker='D', ms=7, label=Players[3])
plt.legend(loc='upper left',bbox_to_anchor=(1,1)) # legend
plt.xticks(list(range(0,9)),Seasons)
plt.show()

In [ ]:
plt.plot(Salary[0],c='Black', ls='--', marker='s', ms=7, label=Players[0])
plt.plot(Salary[1],c='Red', ls='--', marker='o', ms=7, label=Players[1])
plt.plot(Salary[2],c='Green', ls='--', marker='^', ms=7, label=Players[2])
plt.plot(Salary[3],c='Blue', ls='--', marker='D', ms=7, label=Players[3])
plt.legend(loc='upper left',bbox_to_anchor=(1,0)) # legendplt.xticks(list(range(0,9)),Seasons)
plt.show()

In [ ]:
plt.plot(Salary[0],c='Black', ls='--', marker='s', ms=7, label=Players[0])
plt.plot(Salary[1],c='Red', ls='--', marker='o', ms=7, label=Players[1])
plt.plot(Salary[2],c='Green', ls='--', marker='^', ms=7, label=Players[2])
plt.plot(Salary[3],c='Blue', ls='--', marker='D', ms=7, label=Players[3])
plt.legend(loc='upper left',bbox_to_anchor=(0,0)) # legend
plt.xticks(list(range(0,9)),Seasons)
plt.show()

In [ ]:
plt.plot(Salary[0],c='Black', ls='--', marker='s', ms=7, label=Players[0])
plt.plot(Salary[1],c='Red', ls='--', marker='o', ms=7, label=Players[1])
plt.plot(Salary[2],c='Green', ls='--', marker='^', ms=7, label=Players[2])
plt.plot(Salary[3],c='Blue', ls='--', marker='D', ms=7, label=Players[3])
plt.legend(loc='upper right',bbox_to_anchor=(1,1)) # legend
plt.xticks(list(range(0,9)),Seasons)
plt.show()

In [ ]:
plt.plot(Salary[0],c='Black', ls='--', marker='s', ms=7, label=Players[0])
plt.plot(Salary[1],c='Red', ls='--', marker='o', ms=7, label=Players[1])
plt.plot(Salary[2],c='Green', ls='--', marker='^', ms=7, label=Players[2])
plt.plot(Salary[3],c='Blue', ls='--', marker='D', ms=7, label=Players[3])
plt.legend(loc='upper right',bbox_to_anchor=(0.5,0.5)) # legend
plt.xticks(list(range(0,9)),Seasons)
plt.show()

In [ ]:
plt.plot(Salary[0],c='Black', ls='--', marker='s', ms=7, label=Players[0])
plt.plot(Salary[1],c='Red', ls='--', marker='o', ms=7, label=Players[1])
plt.plot(Salary[2],c='Green', ls='--', marker='^', ms=7, label=Players[2])
plt.plot(Salary[3],c='Blue', ls='--', marker='D', ms=7, label=Players[3])
plt.legend(loc='upper left',bbox_to_anchor=(1,1)) # legend
plt.xticks(list(range(0,9)),Seasons)
plt.show()

In [ ]:
plt.plot(Salary[0],c='Black', ls='--', marker='s', ms=7, label=Players[0])
plt.plot(Salary[1],c='Red', ls='--', marker='o', ms=7, label=Players[1])
plt.plot(Salary[2],c='Green', ls='--', marker='^', ms=7, label=Players[2])
plt.plot(Salary[3],c='Blue', ls='--', marker='D', ms=7, label=Players[3])
plt.plot(Salary[4],c='Magenta', ls='--', marker='s', ms=7, label=Players[4])
plt.plot(Salary[5],c='Black', ls='--', marker='o', ms=7, label=Players[5])
plt.plot(Salary[6],c='Red', ls='--', marker='^', ms=7, label=Players[6])
plt.plot(Salary[7],c='Green', ls='--', marker='D', ms=7, label=Players[7])
plt.plot(Salary[8],c='Blue', ls='--', marker='s', ms=7, label=Players[8])
plt.plot(Salary[9],c='Magenta', ls='--', marker='o', ms=7, label=Players[9])
plt.legend(loc='upper left',bbox_to_anchor=(1,1)) # legend
plt.xticks(list(range(0,9)),Seasons)
plt.show()

In [ ]:
# So what is the problem here?
# How do we get to see the Games of all the players
plt.plot(Games[0],c='Black', ls='--', marker='s', ms=7, label=Players[0])
plt.plot(Games[1],c='Red', ls='--', marker='o', ms=7, label=Players[1])
plt.plot(Games[2],c='Green', ls='--', marker='^', ms=7, label=Players[2])
plt.plot(Games[3],c='Blue', ls='--', marker='D', ms=7, label=Players[3])
plt.plot(Games[4],c='Magenta', ls='--', marker='s', ms=7, label=Players[4])
plt.plot(Games[5],c='Black', ls='--', marker='o', ms=7, label=Players[5])
plt.plot(Games[6],c='Red', ls='--', marker='^', ms=7, label=Players[6])
plt.plot(Games[7],c='Green', ls='--', marker='D', ms=7, label=Players[7])
plt.plot(Games[8],c='Blue', ls='--', marker='s', ms=7, label=Players[8])
plt.plot(Games[9],c='Magenta', ls='--', marker='o', ms=7, label=Players[9])
plt.legend(loc='upper left',bbox_to_anchor=(1,1)) # legend
plt.xticks(list(range(0,9)),Seasons)
plt.show()


In [ ]:
# Custom Functionsdef myplot():
plt.plot(Games[0],c='Black', ls='--', marker='s', ms=7, label=Players[0])
plt.plot(Games[1],c='Red', ls='--', marker='o', ms=7, label=Players[1])
plt.plot(Games[2],c='Green', ls='--', marker='^', ms=7, label=Players[2])
plt.plot(Games[3],c='Blue', ls='--', marker='D', ms=7, label=Players[3])
plt.plot(Games[4],c='Magenta', ls='--', marker='s', ms=7, label=Players[4])
plt.plot(Games[5],c='Black', ls='--', marker='o', ms=7, label=Players[5])
plt.plot(Games[6],c='Red', ls='--', marker='^', ms=7, label=Players[6])
plt.plot(Games[7],c='Green', ls='--', marker='D', ms=7, label=Players[7])
plt.plot(Games[8],c='Blue', ls='--', marker='s', ms=7, label=Players[8])
plt.plot(Games[9],c='Magenta', ls='--', marker='o', ms=7, label=Players[9])
plt.legend(loc='upper left',bbox_to_anchor=(1,1)) # legend
plt.xticks(list(range(0,9)),Seasons)
plt.show()

In [ ]:
# Custom Functions def myplot():
plt.plot(Games[0],c='Black', ls='--', marker='s', ms=7, label=Players[0])
plt.plot(Games[1],c='Red', ls='--', marker='o', ms=7, label=Players[1])
plt.plot(Games[2],c='Green', ls='--', marker='^', ms=7, label=Players[2])
plt.plot(Games[3],c='Blue', ls='--', marker='D', ms=7, label=Players[3])
plt.plot(Games[4],c='Magenta', ls='--', marker='s', ms=7, label=Players[4])
plt.plot(Games[5],c='Black', ls='--', marker='o', ms=7, label=Players[5])
plt.plot(Games[6],c='Red', ls='--', marker='^', ms=7, label=Players[6])
plt.plot(Games[7],c='Green', ls='--', marker='D', ms=7, label=Players[7])
plt.plot(Games[8],c='Blue', ls='--', marker='s', ms=7, label=Players[8])
plt.plot(Games[9],c='Magenta', ls='--', marker='o', ms=7, label=Players[9])
plt.legend(loc='upper left',bbox_to_anchor=(1,1)) # legend
plt.xticks(list(range(0,9)),Seasons)
plt.show()myplot()


In [ ]:
playerlist = ['KobeBryant','LeBronJames','DerrickRose']
type(playerlist)
Pdict['KobeBryant']
def myplot(playerlist):
    for name in playerlist:
        plt.plot(Games[Pdict[name]],c='Black',ls='--',marker='s',ms=7,label=name)
        plt.legend(loc='upper left',bbox_to_anchor=(1,1)) # legend
        plt.xticks(list(range(0,9)),Seasons)
        plt.show()
        myplot(playerlist)
        myplot(['KobeBryant','LeBronJames','DerrickRose'])
        myplot(['KobeBryant','DerrickRose'])



In [27]:
def myplot(playerlist):
    Col = {"KobeBryant":'Black',"JoeJohnson":'Red',"LeBronJames":'Green',"CarmeloAnthony":'Blue',
"DwightHoward":'Magenta',
"ChrisBosh":'Black',"ChrisPaul":'Red',"KevinDurant":'Green',"DerrickRose":'Blue',
"DwayneWade":'Magenta'}   
for name in playerlist:
    plt.plot(Games[Pdict[name]],c=Col[name],ls='--',marker='s',ms=7,label=name)
    plt.legend(loc='upper left',bbox_to_anchor=(1,1)) # legend
    plt.xticks(list(range(0,9)),Seasons)
    plt.show()
    myplot(['KobeBryant','LeBronJames','DerrickRose'])
 

NameError: name 'playerlist' is not defined

In [ ]:
def myplot(playerlist):
    Col = {"KobeBryant":'Black',"JoeJohnson":'Red',"LeBronJames":'Green',"CarmeloAnthony":'Blue',"DwightHoward":'Magenta',"ChrisBosh":'Black',"ChrisPaul":'Red',"KevinDurant":'Green',"DerrickRose":'Blue',"DwayneWade":'Magenta'}
Mrk = {"KobeBryant":'s',"JoeJohnson":'o',"LeBronJames":'^',"CarmeloAnthony":'D',"DwightHoward":'s',"ChrisBosh":'o',"ChrisPaul":'^',"KevinDurant":'D',"DerrickRose":'s',"DwayneWade":'o'}
for name in playerlist:
    plt.plot(Games[Pdict[name]],c=Col[name],ls='--',marker=Mrk[name],ms=7,label=name)
    plt.legend(loc='upper left',bbox_to_anchor=(1,1)) # legend
    plt.xticks(list(range(0,9)),Seasons)
    plt.show()
    myplot(['KobeBryant','LeBronJames','DerrickRose'])
    myplot(['KobeBryant','LeBronJames','DerrickRose','JoeJohnson'])

In [ ]:
def myplot(data,playerlist):
    Col = {"KobeBryant":'Black',"JoeJohnson":'Red',"LeBronJames":'Green',"CarmeloAnthony":'Blue',
"DwightHoward":'Magenta',
"ChrisBosh":'Black',"ChrisPaul":'Red',"KevinDurant":'Green',"DerrickRose":'Blue',
"DwayneWade":'Magenta'}
Mrk = {"KobeBryant":'s',"JoeJohnson":'o',"LeBronJames":'^',"CarmeloAnthony":'D',
"DwightHoward":'s',"ChrisBosh":'o',"ChrisPaul":'^',"KevinDurant":'D',"DerrickRose":'s',"DwayneWade":'o'}
for name in playerlist:
    plt.plot(data[Pdict[name]],c=Col[name],ls='--',marker=Mrk[name],ms=7,label=name)
    plt.legend(loc='upper left',bbox_to_anchor=(1,1)) # legend
    plt.xticks(list(range(0,9)),Seasons)
    plt.show()
    myplot(Points,['KobeBryant','LeBronJames','DerrickRose'])
    myplot(Salary,['KobeBryant','LeBronJames','DerrickRose'])
    myplot(FieldGoals,['KobeBryant','LeBronJames','DerrickRose'])
    myplot(FieldGoalAttempts,['KobeBryant','LeBronJames','DerrickRose'])
    myplot(FieldGoals/FieldGoalAttempts,['KobeBryant','LeBronJames','DerrickRose'])
    FieldGoals/FieldGoalAttempts

In [ ]:
def myplot(data,playerlist=Players):
    Col = {"KobeBryant":'Black',"JoeJohnson":'Red',"LeBronJames":'Green',"CarmeloAnthony":'Blue',"DwightHoward":'Magenta',
"ChrisBosh":'Black',"ChrisPaul":'Red',"KevinDurant":'Green',"DerrickRose":'Blue',"DwayneWade":'Magenta'}
Mrk = {"KobeBryant":'s',"JoeJohnson":'o',"LeBronJames":'^',"CarmeloAnthony":'D',"DwightHoward":'s',"ChrisBosh":'o',"ChrisPaul":'^',"KevinDurant":'D',"DerrickRose":'s',"DwayneWade":'o'}
for name in playerlist:
    plt.plot(data[Pdict[name]],c=Col[name],ls='--',marker=Mrk[name],ms=7,label=name)
    plt.legend(loc='upper left',bbox_to_anchor=(1,1)) # legend
    plt.xticks(list(range(0,9)),Seasons)
    plt.show()
    myplot(Salary,['KobeBryant','LeBronJames','DerrickRose'])
    myplot(Salary)
    myplot(Points)
# Insights
myplot(Games)
myplot(Salary)